mmu2108_P8105_HW2
================
2022-10-04

``` r
library(tidyverse)
library(readxl)
```

### Problem 1

Below we import and clean data from
`NYC_Transit_Subway_Entrance_And_Exit_Data.csv`. The process begins with
data import, updates variable names, and selects the columns that will
be used in later parts fo this problem. We update `entry` from `yes` /
`no` to a logical variable. As part of data import, we specify that
`Route` columns 8-11 should be character for consistency with 1-7.

``` r
trans_ent = 
  read_csv(
    "~/Documents/Columbia Grad School/Fall 2022/Data Science/HW/p8105_hw2_mmu2108/NYC_Transit_Subway_Entrance_And_Exit_Data.csv",
    col_types = cols(Route8 = "c", Route9 = "c", Route10 = "c", Route11 = "c")) %>% 
  janitor::clean_names() %>% 
  select(
    line, station_name, station_latitude, station_longitude, 
    starts_with("route"), entry, exit_only, vending, entrance_type, 
    ada) %>% 
  mutate(entry = ifelse(entry == "YES", TRUE, FALSE))
```

As it stands, these data are not “tidy”: route number should be a
variable, as should route. That is, to obtain a tidy dataset we would
need to convert `route` variables from wide to long format. This will be
useful when focusing on specific routes, but may not be necessary when
considering questions that focus on station-level variables.

The following code chunk selects station name and line, and then uses
`distinct()` to obtain all unique combinations. As a result, the number
of rows in this dataset is the number of unique stations.

``` r
trans_ent %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 465 × 2
    ##    station_name             line    
    ##    <chr>                    <chr>   
    ##  1 25th St                  4 Avenue
    ##  2 36th St                  4 Avenue
    ##  3 45th St                  4 Avenue
    ##  4 53rd St                  4 Avenue
    ##  5 59th St                  4 Avenue
    ##  6 77th St                  4 Avenue
    ##  7 86th St                  4 Avenue
    ##  8 95th St                  4 Avenue
    ##  9 9th St                   4 Avenue
    ## 10 Atlantic Av-Barclays Ctr 4 Avenue
    ## # … with 455 more rows

The next code chunk is similar, but filters according to ADA compliance
as an initial step. This produces a dataframe in which the number of
rows is the number of ADA compliant stations.

``` r
trans_ent %>% 
  filter(ada == TRUE) %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 84 × 2
    ##    station_name                   line           
    ##    <chr>                          <chr>          
    ##  1 Atlantic Av-Barclays Ctr       4 Avenue       
    ##  2 DeKalb Av                      4 Avenue       
    ##  3 Pacific St                     4 Avenue       
    ##  4 Grand Central                  42nd St Shuttle
    ##  5 34th St                        6 Avenue       
    ##  6 47-50th Sts Rockefeller Center 6 Avenue       
    ##  7 Church Av                      6 Avenue       
    ##  8 21st St                        63rd Street    
    ##  9 Lexington Av                   63rd Street    
    ## 10 Roosevelt Island               63rd Street    
    ## # … with 74 more rows

To compute the proportion of station entrances / exits without vending
allow entrance, we first exclude station entrances that do not allow
vending. Then, we focus on the `entry` variable – this logical, so
taking the mean will produce the desired proportion (recall that R will
coerce logical to numeric in cases like this).

``` r
trans_ent %>% 
  filter(vending == "NO") %>% 
  pull(entry) %>% 
  mean
```

    ## [1] 0.3770492

Lastly, we write a code chunk to identify stations that serve the A
train, and to assess how many of these are ADA compliant. As a first
step, we tidy the data as alluded to previously; that is, we convert
`route` from wide to long format. After this step, we can use tools from
previous parts of the question (filtering to focus on the A train, and
on ADA compliance; selecting and using `distinct` to obtain dataframes
with the required stations in rows).

``` r
trans_ent %>% 
  pivot_longer(
    route1:route11,
    names_to = "route_num",
    values_to = "route") %>% 
  filter(route == "A") %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 60 × 2
    ##    station_name                  line           
    ##    <chr>                         <chr>          
    ##  1 Times Square                  42nd St Shuttle
    ##  2 125th St                      8 Avenue       
    ##  3 145th St                      8 Avenue       
    ##  4 14th St                       8 Avenue       
    ##  5 168th St - Washington Heights 8 Avenue       
    ##  6 175th St                      8 Avenue       
    ##  7 181st St                      8 Avenue       
    ##  8 190th St                      8 Avenue       
    ##  9 34th St                       8 Avenue       
    ## 10 42nd St                       8 Avenue       
    ## # … with 50 more rows

``` r
trans_ent %>% 
  pivot_longer(
    route1:route11,
    names_to = "route_num",
    values_to = "route") %>% 
  filter(route == "A", ada == TRUE) %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 17 × 2
    ##    station_name                  line            
    ##    <chr>                         <chr>           
    ##  1 14th St                       8 Avenue        
    ##  2 168th St - Washington Heights 8 Avenue        
    ##  3 175th St                      8 Avenue        
    ##  4 34th St                       8 Avenue        
    ##  5 42nd St                       8 Avenue        
    ##  6 59th St                       8 Avenue        
    ##  7 Inwood - 207th St             8 Avenue        
    ##  8 West 4th St                   8 Avenue        
    ##  9 World Trade Center            8 Avenue        
    ## 10 Times Square-42nd St          Broadway        
    ## 11 59th St-Columbus Circle       Broadway-7th Ave
    ## 12 Times Square                  Broadway-7th Ave
    ## 13 8th Av                        Canarsie        
    ## 14 Franklin Av                   Franklin        
    ## 15 Euclid Av                     Fulton          
    ## 16 Franklin Av                   Fulton          
    ## 17 Howard Beach                  Rockaway

### Problem 2

``` r
mr_trash = read_excel("~/Documents/Columbia Grad School/Fall 2022/Data Science/HW/p8105_hw2_mmu2108/trash_wheel_collection_data.xlsx", sheet = "Mr. Trash Wheel") %>% 
  janitor::clean_names() %>%
  drop_na(, dumpster) %>%
  select(-x15, -x16) %>%
  mutate(, year = as.integer(year)) %>%
  mutate(, sports_balls = round(sports_balls, digits = 0),
         sports_balls = as.integer(sports_balls)) %>%
  mutate(vessel = 'mr')
```

    ## New names:
    ## • `` -> `...15`
    ## • `` -> `...16`

``` r
prof_trash = read_excel("~/Documents/Columbia Grad School/Fall 2022/Data Science/HW/p8105_hw2_mmu2108/trash_wheel_collection_data.xlsx", sheet = "Professor Trash Wheel") %>% 
  janitor::clean_names() %>%
  drop_na(, dumpster) %>%
  mutate(vessel = 'professor')
```

``` r
trashwheel = 
  bind_rows(mr_trash, prof_trash) %>%
  janitor::clean_names() %>%
  select(vessel, everything()) 
```

In total, there are 641 dumpster observations among Mr. Trash Wheel and
Professor Trash Wheel. There are 15 total variables in the combined
dataset: the vessel (‘mr’ for Mr. Trash Wheel or ‘prof’ for Professor
Trash Wheel), ‘dumpster’ number, dates variables, several variables for
weight and number of item types collected, and homes powered. It is
notable that Professor Trash Wheel did not collect any sports balls,
thus all observations are marked as ‘NA’ in the combined ‘trashwheel’
dataset.

Professor Trash Wheel collected a total of 190.12 tons of trash. There
was a total of 856 sports balls collected by Mr. Trash Wheel in 2020.

### Problem 3

``` r
pols_tidy = 
  read_csv(
    "~/Documents/Columbia Grad School/Fall 2022/Data Science/HW/p8105_hw2_mmu2108/fivethirtyeight_datasets/pols-month.csv") %>%
  janitor::clean_names() %>%
  separate(mon, into = c("year", "month", "day"), sep = "-") %>%
  mutate(month = as.numeric(month)) %>%
  arrange(year, month) %>%
  mutate(month = month.name[month]) %>%
  mutate(year = as.numeric(year)) %>%
  unite(president, prez_gop, prez_dem, remove = TRUE) %>%
  select(-day)
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
snp_tidy = 
  read_csv(
    "~/Documents/Columbia Grad School/Fall 2022/Data Science/HW/p8105_hw2_mmu2108/fivethirtyeight_datasets/snp.csv") %>%
  janitor::clean_names() %>%
  separate(date, into = c("month", "day", "year"), sep = "/") %>%
  mutate(year = as.integer(year)) %>%
  mutate(year = ifelse(year <= 15, year + 2000, year + 1900)) %>%
  mutate(month = as.numeric(month)) %>%
  arrange(year, month) %>%
  mutate(month = month.name[month]) %>%
  select(year, month, everything()) %>%
  mutate(year = as.numeric(year)) %>%
  select(-day)
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
unemploy_tidy = 
  read_csv(
    "~/Documents/Columbia Grad School/Fall 2022/Data Science/HW/p8105_hw2_mmu2108/fivethirtyeight_datasets/unemployment.csv") %>%
  janitor::clean_names() %>%
  pivot_longer(
    jan:dec,
    names_to = "month",
    values_to = "unemployment"
  ) %>%
  mutate(month = match(month, tolower(month.abb))) %>%
  mutate(month = month.name[month]) %>%
  mutate(year = as.numeric(year))
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
fivethirtyeight_merge = 
  merge(pols_tidy, snp_tidy, by = c("year", "month"))
  
fivethirtyeight_merge = 
  merge(fivethirtyeight_merge, unemploy_tidy, by = c("year", "month")) %>%
  arrange(year, match(month, month.name))
```

The pols dataset includes counts of Republican and Democratic senators
(sen_gop, sen_dem), representatives (rep_gop, rep_dem), and political
party of the president (originally prez_gop, prez_dem, but combined into
1 president variable). There were 822 month observations, with dates
ranging from January 1947 to June 2015. There were a total of 9
variables including year and month.

The snp dataset includes the ‘close’ variable. It includes 787 monthly
observations, with dates ranging from January 1950 to July 2015. There
were a total of 3 variables including year and month.

The unemployment dataset includes an “unemployment” percentage variable.
It includes 810 observations, with dates ranging from January 1948 to
June 2015. There were a total of 3 variables including year and month.
